blueprint:
  name: Zigbee2MQTT - Philips Hue smart button
  description: >-
    Integrate Philips Hue smart button into Home Assistant to create a powerful remote control,
    supporting single press and hold functionality.
  domain: automation
  input:
    smart_button:
      name: Smart button
      description: Hue smart button to use (pick the sensor that end with _action).
      selector:
        entity:
          integration: mqtt
          domain: sensor
    press_action:
      name: Press
      description: Action to run on button press.
      default: []
      selector:
        action:
    hold_action:
      name: Hold
      description: Action to run on button hold.
      default: []
      selector:
        action:
    hold_cooldown:
      name: Hold cool down
      description: Prevent this automation from being ran more often than only once while in this cool down.
      default: 3
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input smart_button
  to:
    - "on"
    - "off"
    - "hold"

action:
  - variables:
      to_state: "{{ trigger.to_state.state }}"

  - choose:
    # Button is being pressed.
    - conditions:
        - "{{ to_state in ['on', 'off'] }}"
      sequence: !input press_action

    # Button is being hold.
    - conditions:
        - "{{ to_state == 'hold' }}"
      sequence: 
        - choose:
          - conditions:
              - "{{ true }}"
            sequence: !input hold_action
        - delay:
           seconds: !input hold_cooldown
